//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Persona
    {
        public int Id_usuario { get; set; }
        [Required(ErrorMessage = "* Campo obligatorio")]
        [RegularExpression(@"^[a-zA-ZÀ-ÿ\u00f1\u00d1]+(\s*[a-zA-ZÀ-ÿ\u00f1\u00d1]*)*[a-zA-ZÀ-ÿ\u00f1\u00d1]+$",
         ErrorMessage = "Ingrese un Nombre Válido")]
        public string PrimerNombre { get; set; }
        [RegularExpression(@"^[a-zA-ZÀ-ÿ\u00f1\u00d1]+(\s*[a-zA-ZÀ-ÿ\u00f1\u00d1]*)*[a-zA-ZÀ-ÿ\u00f1\u00d1]+$",
        ErrorMessage = "Ingrese un Nombre Válido")]
        public string SegundoNombre { get; set; }
        [Required(ErrorMessage = "* Campo obligatorio")]
        [RegularExpression(@"^[a-zA-ZÀ-ÿ\u00f1\u00d1]+(\s*[a-zA-ZÀ-ÿ\u00f1\u00d1]*)*[a-zA-ZÀ-ÿ\u00f1\u00d1]+$",
         ErrorMessage = "Ingrese un Apellido Válido")]
        public string PrimerApellido { get; set; }
        [RegularExpression(@"^[a-zA-ZÀ-ÿ\u00f1\u00d1]+(\s*[a-zA-ZÀ-ÿ\u00f1\u00d1]*)*[a-zA-ZÀ-ÿ\u00f1\u00d1]+$",
        ErrorMessage = "Ingrese un Apellido Válido")]
        public string SegundoApellido { get; set; }
        [Required(ErrorMessage = "* Campo obligatorio")]
        [RegularExpression(@"^[a-zA-ZÀ-ÿ\u00f1\u00d1]+(\s*[a-zA-ZÀ-ÿ\u00f1\u00d1]*)*[a-zA-ZÀ-ÿ\u00f1\u00d1]+$",
         ErrorMessage = "Ingrese un Ciudad Válido")]
        public string Ciudad { get; set; }
        [Required(ErrorMessage = "* Campo obligatorio")]
        [RegularExpression(@"^[0-9]+$",
         ErrorMessage = "Ingrese valor Válido")]
        public int Edad { get; set; }
    }
}
