//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Persona
    {
        [Required(ErrorMessage = "* Campo obligatorio")]
        public string Identificacion { get; set; }

        [Required(ErrorMessage = "* Campo obligatorio")]
        [RegularExpression(@"^[a-zA-ZÀ-ÿ\u00f1\u00d1]+(\s*[a-zA-ZÀ-ÿ\u00f1\u00d1]*)*[a-zA-ZÀ-ÿ\u00f1\u00d1]+$",
         ErrorMessage = "Ingrese un Nombre Válido")]
        public string PrimerNombre { get; set; }

        [Required(ErrorMessage = "* Campo obligatorio")]
        [RegularExpression(@"^[a-zA-ZÀ-ÿ\u00f1\u00d1]+(\s*[a-zA-ZÀ-ÿ\u00f1\u00d1]*)*[a-zA-ZÀ-ÿ\u00f1\u00d1]+$",
        ErrorMessage = "Ingrese un Nombre Válido")]
        public string PrimerApellido { get; set; }


        [Required(ErrorMessage = "* Campo obligatorio")]
        public System.DateTime Fecha_de_nacimiento { get; set; }


        [Required(ErrorMessage = "* Campo obligatorio")]
        [RegularExpression(@"^[1-14]+$",
         ErrorMessage = "Ingrese valor Válido")]
        public int Direccion { get; set; }


        [Required(ErrorMessage = "* Campo obligatorio")]
        public string Correo { get; set; }

        [Required(ErrorMessage = "* Campo obligatorio")]
        public string Telefono { get; set; }
    }
}
